version: "2"
services:

  #ssl:
    #image: fballiano/nginx-ssl-for-magento2
    #depends_on:
      #- webserver
    #links:
      #- webserver
    #ports:
      #- "443:443"

  webserver:
    image: "nginx:alpine"
    container_name: ves_nginx
    ports:
      - "80:80"
    depends_on:
      - "appserver"
    volumes:
      - "./env/webserver/etc/nginx.conf:/etc/nginx/nginx.conf"
    volumes_from:
      - "appserver"
    env_file:
      - ./global.env


  appserver:
    image: "mrtuvn/php:7.1"
    volumes:
      - "./src:/mnt/www"
      - "./env/appserver/etc/php.ini:/usr/local/etc/php/php.ini"
    depends_on:
      - "database"
      #- "mail"
      - "cache"
      - "fpc"
      - "session"
      - "messagequeue"

  appserver_debug:
    image: "mrtuvn/php:7.1-xdebug"
    volumes_from:
      - "appserver"
    depends_on:
      - "appserver"

  database:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql"
      - "./env/database/etc/mysql/my.cnf:/etc/mysql/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "magento2"
      MYSQL_USER: "magento2"
      MYSQL_PASSWORD: "magento2"
      TERM: "meh"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: m2docker_phpmyadmin
    environment:
     - PMA_HOST=localhost
    restart: always
    links:
      - database
    ports:
     - "8081:8081"
    volumes:
     - /sessions

  #mail:
    #image: "vnecoms/mailcatcher"
    #ports:
      #- "1080:80"

  cache:
    image: "redis:alpine"

  fpc:
    image: "redis:alpine"

  session:
    image: "redis:alpine"

  messagequeue:
    image: "rabbitmq:management"
    ports:
     - "15672:15672"

  #cron:
    #image: meanbee/magento2-php:7.0-cli
    #hostname: magento2-cron.docker
    #command: run-cron
    #environment:
      #- ENABLE_SENDMAIL=true
    #volumes_from:
      #- appdata
    #links:
      #- db
